#!/usr/bin/env -S pwsh -File

function Test-NovaCliNoUpdateResult {
    param(
        [string]$Command,
        [object]$Result
    )

    if ($Command -ne 'update' -or $null -eq $Result) {
        return $false
    }

    $propertyNames = @($Result.PSObject.Properties.Name)
    return ($propertyNames -contains 'UpdateAvailable') -and ($propertyNames -contains 'CurrentVersion') -and -not $Result.UpdateAvailable
}

function Write-NovaCliCommandResult {
    param(
        [string]$Command,
        [object]$Result
    )

    if (Test-NovaCliNoUpdateResult -Command $Command -Result $Result) {
        Write-Output "You're up to date!"
        Write-Output "$( $Result.ModuleName ) $( $Result.CurrentVersion ) is currently the newest version available."
        return
    }

    $Result
}

$Command = if ($args.Count -gt 0) {
    $args[0]
}
else {
    '--help'
}

$Arguments = if ($args.Count -gt 1) {
    @($args[1..($args.Count - 1)])
}
else {
    @()
}

$forwardVerbose = $false
$forwardWhatIf = $false
$forwardConfirm = $false
$remainingArguments = New-Object 'System.Collections.Generic.List[string]'

foreach ($argument in $Arguments) {
    switch -Regex ($argument) {
        '^(--verbose|-Verbose)$' {
            $forwardVerbose = $true
            continue
        }
        '^-WhatIf$' {
            $forwardWhatIf = $true
            continue
        }
        '^-Confirm$' {
            $forwardConfirm = $true
            continue
        }
        default {
            $remainingArguments.Add($argument)
        }
    }
}

$Arguments = @($remainingArguments)

Import-Module NovaModuleTools -Force

$invokeParameters = @{
    Command = $Command
    Arguments = @($Arguments)
}

$originalCliConfirmSetting = $env:NOVA_CLI_CONFIRM_BUMP

if ($forwardVerbose) {
    $invokeParameters.Verbose = $true
}

if ($forwardWhatIf) {
    $invokeParameters.WhatIf = $true
}

if ($forwardConfirm -and $Command -eq 'bump') {
    $env:NOVA_CLI_CONFIRM_BUMP = '1'
}
elseif ($forwardConfirm) {
    $invokeParameters.Confirm = $true
}

try {
    $result = Invoke-NovaCli @invokeParameters
    Write-NovaCliCommandResult -Command $Command -Result $result
}
finally {
    if ($null -eq $originalCliConfirmSetting) {
        Remove-Item Env:NOVA_CLI_CONFIRM_BUMP -ErrorAction SilentlyContinue
    }
    else {
        $env:NOVA_CLI_CONFIRM_BUMP = $originalCliConfirmSetting
    }
}
