name: Run Tests

on:
  push:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 📦 Install required modules from PSGallery
        run: |
          Install-PSResource -Repository PSGallery -Name NovaModuleTools -TrustRepository
          Install-PSResource -Repository PSGallery -Name Microsoft.PowerShell.PlatyPS -TrustRepository
          Install-PSResource -Repository PSGallery -Name Pester -TrustRepository

      - name: 🏗️ Build Module
        run: Invoke-NovaBuild -Verbose

      - name: 🧪 Run Pester Tests
        run: Test-NovaBuild

      - name: 📝 Generate Report
        continue-on-error: true
        run: |
          $reportLines = @('## Output Files 📁', '')
          $files = Get-ChildItem -Path ./dist -Recurse -ErrorAction SilentlyContinue | Sort-Object FullName

          if ($files) {
            $reportLines += '| Name | Directory |'
            $reportLines += '| --- | --- |'
            $reportLines += $files | ForEach-Object {
              $name = ('' + $_.Name).Replace('|', '\|')
              $directory = ('' + $_.Directory).Replace('|', '\|')
              "| $name | $directory |"
            }
          }
          else {
            $reportLines += 'No files found in `./dist`.'
          }

          $report = $reportLines -join [Environment]::NewLine
          Add-Content -LiteralPath $env:GITHUB_STEP_SUMMARY -Value $report
          Write-Output $report
